---
satellite_prepare_ipa_default_bind_policy: >-
  grant {{ ipaclient_realm }} krb5-self * A; grant {{ ipaclient_realm }} krb5-self * AAAA;
  grant {{ ipaclient_realm }} krb5-self * SSHFP;
satellite_prepare_foreman_proxy_realm_principal: ""
satellite_prepare_foreman_proxy_bind_update_policy: >-
  {{ satellite_prepare_ipa_default_bind_policy }} grant
  {{ satellite_prepare_foreman_proxy_realm_principal }}\@{{ ipaclient_realm }}
  wildcard * ANY;

satellite_prepare_keytab_path: ""
satellite_prepare_skip_prepare_realm: false

satellite_prepare_ipaclient_domain: "{{ ipaclient_domain }}"
satellite_prepare_ipa_server_ca_path: "{{ ipa_server_ca_path }}"
satellite_prepare_ipa_client_trust_path: "{{ ipa_client_trust_path }}"
