- name: Block for create a cronjob for token refresh
  become: true
  block:
    - name: Create a cron job for token refresh
      ansible.builtin.cron:
        name: RH API token refresh
        weekday: "*"
        minute: "0"
        hour: "09"
        user: root
        job: >-
          curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token\
          -d client_id="cloud-services" -d refresh_token="{{ token.value }}" --fail --silent --show-error --output /dev/null
        cron_file: rh-token-refresh-{{ token.name }}

    - name: Update cron file permission
      ansible.builtin.file:
        path: "/etc/cron.d/rh-token-refresh-{{ token.name }}"
        mode: "0644"
