---
- name: Fetch CCV info
  register: __result
  theforeman.foreman.content_view_info:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_organization }}"
    name: "{{ satellite_config_ccv_name }}"

- name: Ensure CV is published
  loop: "{{ __result.content_view.components }}"
  loop_control:
    loop_var: component
  theforeman.foreman.content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_organization }}"
    content_view: "{{ component.content_view.name }}"
    description: "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

- name: Ensure CCV is promoted to lifecycle
  theforeman.foreman.content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_organization }}"
    content_view: "{{ satellite_config_ccv_name }}"
    description: "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
    lifecycle_environments:
      - Dev
