---
- name: Ensure custom product - {{ custom_product.name }}
  theforeman.foreman.product:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_organization }}"
    name: "{{ custom_product.name }}"
    state: "{{ custom_product.state | default(omit) }}"

- name: Ensure the state the repositories required for the custom product.
  ansible.builtin.include_tasks: satellite_ensure_custom_product_repo.yml
  loop: "{{ custom_product.repositories }}"
  loop_control:
    loop_var: custom_product_repository
  when: custom_product.repositories is defined
