---
galaxy_info:
  author: Showroom Project Team
  description: This repo first and configures git to the host and then clone the given repository, add files, commit, and push changes to remote repository.
  company: Red Hat, Inc.
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
collections:
  - ansible.builtin
  - community.general
