---
galaxy_info:
  author: Showroom Project Team
  description: This roles installs defined packages and copies private key when required.
  company: Red Hat, Inc.
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
