---
galaxy_info:
  author: Showroom Project Team
  description: This role deploy/deletes host (VM) on defined host group in location, organization, with using specified image in the compute resource.
  company: Red Hat, Inc.
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
collections:
  - redhat.satellite
