---
galaxy_info:
  author: Showroom Project Team
  description: This role signs Red Hat Identity Management (IdM) CSR with rootCA certificate.
  company: Red Hat, Inc.
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
collections:
  - community.builtin
  - community.crypto
