---
- name: Create IDM server
  hosts: "{{ host | default('localhost') }}"
  gather_facts: true

  roles:
    - role: redhat.rhel_idm.ipaserver
      state: present # noqa var-naming[no-role-prefix]
      when: create_ipaserver| bool()
      become: true
      vars:
        ipaserver_external_cert_files: "{{ ipaserver_chain_cert_path }}"

  post_tasks:
    - name: Replace the content of /etc/named/ipa-options-ext.conf
      become: true
      ansible.builtin.copy:
        dest: /etc/named/ipa-options-ext.conf
        mode: "0640"
        content: |
          allow-recursion { trusted_network; };
          allow-query-cache { trusted_network; };
          listen-on-v6 { any; };
          dnssec-validation yes;

    - name: Replace the content of /etc/named/ipa-ext.conf
      become: true
      ansible.builtin.copy:
        dest: /etc/named/ipa-ext.conf
        mode: "0640"
        content: |
          acl "trusted_network" {
           localnets;
           localhost;
          {% for network in azure_networks %}
           {{ network.subnet }};
          {% endfor %}
          };

    - name: Restart ipa service
      become: true
      ansible.builtin.systemd:
        name: ipa
        state: restarted
