---
- name: Manage Azure Snapshot
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  roles:
    - role: azure_snapshot
      when:
        - azure_snapshot | bool()
      tags: azure_snapshot
      delegate_to: localhost
