---
- name: Create Managed Disk
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  roles:
    - role: azure_managed_disk
      when:
        - azure_managed_disk | bool()
      tags: azure_managed_disk
      delegate_to: localhost
