---
- name: Create VM from Satellite
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  roles:
    - role: satellite_host_deploy
      when: satellite_host_deploy | bool()
      tags: satellite_host_deploy
      delegate_to: "{{ groups['bastion'][0] }}"
