---
- name: Sign IDM CSR approve
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  roles:
    - role: pki_idm_csr_approve
      when: pki_idm_csr_approve | bool()
      become: true
