---
- name: Config vnet
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  pre_tasks:
    - name: Get IdM DNS IPs
      run_once: true # noqa run-once[task]
      block:
        - name: Get IP - "{{ groups.ipaserver | first }}"
          ansible.builtin.setup:
          delegate_to: "{{ groups.ipaserver | first }}"
          register: __ipaserver_facts

        - name: Set ipaclient_dns_servers
          ansible.builtin.set_fact:
            ipaclient_dns_servers: "{{ [__ipaserver_facts.ansible_facts.ansible_default_ipv4.address] }}"

        - name: Get IP - "{{ groups.ipareplicas | first }}"
          ansible.builtin.setup:
          delegate_to: "{{ groups.ipareplicas | first }}"
          register: __ipareplica_facts

        - name: Set ipaclient_dns_servers
          ansible.builtin.set_fact:
            ipaclient_dns_servers: "{{ ipaclient_dns_servers + [__ipareplica_facts.ansible_facts.ansible_default_ipv4.address] }}"

        - name: Set ipaclient_dns_servers to azure_vnet_dns_servers
          ansible.builtin.set_fact:
            azure_vnet_dns_servers: "{{ ipaclient_dns_servers }}"

  tasks:
    - name: Remove Private DNS zone links
      ansible.builtin.import_role:
        name: azure_dns
        tasks_from: private_dns_zone_link.yml
      delegate_to: localhost
      vars:
        azure_dns_private_dns_zone_state: absent

    - name: Remove Private DNS zone
      ansible.builtin.import_role:
        name: azure_dns
        tasks_from: private_dns_zone.yml
      delegate_to: localhost
      vars:
        azure_dns_private_dns_zone_state: absent

    - name: Remove Private DNS zone
      ansible.builtin.import_role:
        name: azure_network
      delegate_to: localhost
      vars:
        vnet_peering: false # noqa var-naming[no-role-prefix]
        manage_nsg: false # noqa var-naming[no-role-prefix]
        manage_subnet: false # noqa var-naming[no-role-prefix]
