---
- name: Configure Satellite
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  roles:
    - role: satellite_config
      tags: satellite_config
      when: satellite_config | bool()
