---
- name: Create Public Trusted SSL Certificate Create
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  roles:
    - role: public_certificate
      become: true
      when: public_certificate | bool()
      tags: public_certificate
