---
- name: Satellite - Installation
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  roles:
    - role: satellite_prepare
      when: satellite_prepare | bool()
      become: true

    - role: redhat.satellite_operations.installer
      when: satellite_operations | bool()
      become: true
