---
- name: Enable Live Kernel
  hosts: "{{ host | default('localhost') }}"
  gather_facts: true

  tasks:
    - name: Block for Live Kernel Patching
      become: true
      block:
        - name: Ensure kpatch package is installed
          ansible.builtin.package:
            name: kpatch
            state: present

        - name: Deploy / update related Kernel Patch for Live Kernel Patching
          ansible.builtin.package:
            name: "kpatch-patch = {{ ansible_kernel }}"
            state: "{{ package_state | default(omit) }}"
          register: __package_install

        - name: Get status of kpatch-dnf
          ansible.builtin.command:
            cmd: "dnf kpatch status"
          register: __status_dnf_kpatch
          changed_when: false

        - name: Enable DNF plugin for auto install live patches
          ansible.builtin.command:
            cmd: "dnf -y kpatch auto"
          changed_when: true
          when: "'Kpatch update setting: manual' in __status_dnf_kpatch.stdout"

      rescue:
        - name: Rescue message
          ansible.builtin.debug:
            msg: "No kernel live patch update package exist or system is not subscribed to the repository"
