---
- name: Configure Squid
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  roles:
    - role: manage_squid
      become: true
      when: manage_squid | bool()
      tags: manage_squid
