---
- name: Add temp host
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Add a host to group
      ansible.builtin.add_host:
        name: "{{ host_to_add }}"
        groups: "{{ group_to_add }}"
