---
- name: IDM replicas VM - Create
  ansible.builtin.import_playbook: function_azure_vm_create.yml
  when:
    - bootstrap_target is defined
    - bootstrap_target == "azure"
  vars:
    host: ipareplicas
  tags:
    - idm_vm_create

- name: IDM VM - Check if Reachable
  ansible.builtin.import_playbook: toolbox_vm_wait_response.yml
  vars:
    host: ipareplicas
  tags:
    - idm_vm_create

- name: IDM VM - Post Configure
  ansible.builtin.import_playbook: function_vm_post_configure.yml
  vars:
    host: ipareplicas
  tags:
    - idm_vm_post_conf

- name: IDM VM - IDM Deploy Replica
  ansible.builtin.import_playbook: function_idm_ipareplicas_install.yml
  vars:
    host: ipareplicas
  tags:
    - idm_install_replica
