---
- name: "Workload Intra - Create Temp Host"
  ansible.builtin.import_playbook: toolbox_add_temp_host_to_group.yml
  vars:
    host: bastion
    host_to_add: temp_host_workload_servers_intra
    group_to_add: workload_servers_intra
  tags:
    - workload_intra_temp_host

- name: "Workload Intra - Create Network"
  ansible.builtin.import_playbook: function_azure_network_create.yml
  when:
    - bootstrap_target is defined
    - bootstrap_target == "azure"
  vars:
    host: temp_host_workload_servers_intra
  tags:
    - workload_intra_network_create

- name: "Workload Intra - Create Images"
  ansible.builtin.import_playbook: function_imagebuilder_create.yml
  vars:
    host: temp_host_workload_servers_intra
  tags:
    - workload_intra_images_create
