---
- name: Workload DMZ - Create Temp Host for Management
  ansible.builtin.import_playbook: toolbox_add_temp_host_to_group.yml
  vars:
    host: bastion
    host_to_add: temp_host_mgmt_tools_dmz
    group_to_add: mgmt_tools_dmz
  tags:
    - workload_dmz_temp_host_mgmt

- name: Workload DMZ - Create Network for Management
  ansible.builtin.import_playbook: function_azure_network_create.yml
  when:
    - bootstrap_target is defined
    - bootstrap_target == "azure"
  vars:
    host: temp_host_mgmt_tools_dmz
  tags:
    - workload_dmz_network_create_mgmt

- name: Workload DMZ - Create Images for Management
  ansible.builtin.import_playbook: function_imagebuilder_create.yml
  vars:
    host: temp_host_mgmt_tools_dmz
  tags:
    - workload_dmz_images_create_mgmt

- name: Workload DMZ - Create Temp Host for Workloads
  ansible.builtin.import_playbook: toolbox_add_temp_host_to_group.yml
  vars:
    host: bastion
    host_to_add: temp_host_workload_servers_dmz
    group_to_add: workload_servers_dmz
  tags:
    - workload_dmz_temp_host_workloads

- name: Workload DMZ - Create Network for Workloads
  ansible.builtin.import_playbook: function_azure_network_create.yml
  when:
    - bootstrap_target is defined
    - bootstrap_target == "azure"
  vars:
    host: temp_host_workload_servers_dmz
  tags:
    - workload_dmz_network_create_workloads

- name: Workload DMZ - Create Images for Workloads
  ansible.builtin.import_playbook: function_imagebuilder_create.yml
  vars:
    host: temp_host_workload_servers_dmz
  tags:
    - workload_dmz_images_create_workloads
