---
- name: Bastion VM - Create
  ansible.builtin.import_playbook: function_azure_vm_create.yml
  when:
    - bootstrap_target is defined
    - bootstrap_target == "azure"
  vars:
    host: bastion
  tags:
    - bastion_vm_create
    - bastion_vm_post_conf
    - bastion_vm_conf_squid

- name: Bastion VM - Check if Reachable
  ansible.builtin.import_playbook: toolbox_vm_wait_response.yml
  vars:
    host: bastion
  tags:
    - bastion_vm_create
    - bastion_vm_post_conf
    - bastion_vm_conf_squid

- name: Bastion VM - Post Configure
  ansible.builtin.import_playbook: function_vm_post_configure.yml
  vars:
    host: bastion
  tags:
    - bastion_vm_post_conf
    - bastion_vm_conf_squid

- name: Bastion VM - Configure Squid
  ansible.builtin.import_playbook: function_squid_configure.yml
  vars:
    host: bastion
  tags:
    - bastion_vm_conf_squid
