---
# tasks file for satellite_host_deploy
- name: Create a Satellite Host
  when: ( satellite_host_deploy_state is defined and satellite_host_deploy_state == "present" ) or (satellite_host_deploy_state is not defined)
  awx.awx.host:
    username: "{{ hostvars[groups['satellite'][0]]['satellite_username'] }}"
    password: "{{ hostvars[groups['satellite'][0]]['satellite_password'] }}"
    server_url: "{{ hostvars[groups['satellite'][0]]['satellite_server_url'] }}"
    name: "{{ inventory_hostname }}"
    organization: "{{ satellite_host_deploy_organization }}"
    location: "{{ satellite_host_deploy_location }}"
    hostgroup: "{{ satellite_host_deploy_hostgroup }}"
    compute_attributes: "{{ satellite_host_deploy_compute_attributes }}"
    compute_resource: "{{ satellite_host_deploy_compute_resource }}"
    image: "{{ satellite_host_deploy_image }}"
    state: "{{ satellite_host_deploy_state | default(omit) }}"
    compute_profile: "{{ satellite_host_compute_profile }}"

- name: Delete a Satellite Host
  when: satellite_host_deploy_state is defined and satellite_host_deploy_state == "absent"
  awx.awx.host:
    username: "{{ hostvars[groups['satellite'][0]]['satellite_username'] }}"
    password: "{{ hostvars[groups['satellite'][0]]['satellite_password'] }}"
    server_url: "{{ hostvars[groups['satellite'][0]]['satellite_server_url'] }}"
    name: "{{ inventory_hostname }}"
    state: "{{ satellite_host_deploy_state }}"
