---
- name: Configure Controller License
  ansible.builtin.import_role:
    name: infra.controller_configuration.license
  when: controller_license is defined
  tags: aap_config_license

- name: Configure Private Hub Remote Repository
  ansible.builtin.import_role:
    name: infra.ah_configuration.collection_remote
  when: ah_collection_remotes is defined
  tags: aap_config_collection_remote

- name: Configure Private Hub Repository
  ansible.builtin.import_role:
    name: infra.ah_configuration.collection_repository
  when: ah_collection_repositories is defined
  tags: aap_config_collection_repository

- name: Configure Private Hub Repository Sync
  ansible.builtin.import_role:
    name: infra.ah_configuration.collection_repository_sync
  when: (ah_collection_remotes is defined) and aap_config_pah_repo_sync | bool()
  tags: aap_config_collection_repository_sync

- name: Configure Private Hub Execution Environment Registry
  ansible.builtin.import_role:
    name: infra.ah_configuration.ee_registry
  when: ah_ee_registries is defined
  tags: aap_config_ah_ee_registry

- name: Configure Private Hub Execution Environment Registry Sync
  ansible.builtin.import_role:
    name: infra.ah_configuration.ee_registry_sync
  when: ah_ee_registries is defined
  tags: aap_config_ah_ee_registry_sync

- name: Configure Private Hub Execution Environment Repository
  ansible.builtin.import_role:
    name: infra.ah_configuration.ee_repository
  when: ah_ee_repositories is defined
  tags: aap_config_ah_ee_repository

- name: Configure Private Hub Execution Environment Repository Sync
  ansible.builtin.import_role:
    name: infra.ah_configuration.ee_repository_sync
  when: ah_ee_repositories is defined
  tags: aap_config_ah_ee_repository_sync

- name: Create Custom EE
  ansible.builtin.include_tasks: custom_ee.yml
  when: ee_list is defined
  tags: aap_config_custom_ee

- name: Configure Controller Settings
  ansible.builtin.import_role:
    name: infra.controller_configuration.settings
  when: controller_settings is defined
  tags: aap_config_settings

- name: Configure Controller Instance Groups
  ansible.builtin.import_role:
    name: infra.controller_configuration.instance_groups
  when: controller_instance_groups is defined
  tags: aap_config_instance_groups

- name: Configure Controller Organizations
  ansible.builtin.import_role:
    name: infra.controller_configuration.organizations
  when: controller_organizations is defined
  tags: aap_config_organizations

- name: Configure Controller Users
  ansible.builtin.import_role:
    name: infra.controller_configuration.users
  when: controller_user_accounts is defined
  tags: aap_config_users

- name: Configure Controller Teams
  ansible.builtin.import_role:
    name: infra.controller_configuration.teams
  when: controller_teams is defined
  tags: aap_config_teams

- name: Configure Controller Roles
  ansible.builtin.import_role:
    name: infra.controller_configuration.roles
  when: controller_roles is defined
  tags: aap_config_roles

- name: Configure Controller Credential Types
  ansible.builtin.import_role:
    name: infra.controller_configuration.credential_types
  when: controller_credential_types is defined
  tags: aap_config_credential_types

- name: Configure Controller Credentials
  ansible.builtin.import_role:
    name: infra.controller_configuration.credentials
  when: controller_credentials is defined
  tags: aap_config_credentials

- name: Configure Controller Inventories
  ansible.builtin.import_role:
    name: infra.controller_configuration.inventories
  when: controller_inventories is defined
  tags: aap_config_inventories

- name: Configure Controller Execution Environments
  ansible.builtin.import_role:
    name: infra.controller_configuration.execution_environments
  when: controller_execution_environments is defined
  tags: aap_config_execution_environments

- name: Configure Controller Notification Templates
  ansible.builtin.import_role:
    name: infra.controller_configuration.notification_templates
  when: controller_notifications is defined
  tags: aap_config_notification_templates

- name: Configure Controller Projects
  ansible.builtin.import_role:
    name: infra.controller_configuration.projects
  when: controller_projects is defined
  tags: aap_config_projects

- name: Configure Controller Inventory Sources
  ansible.builtin.import_role:
    name: infra.controller_configuration.inventory_sources
  when: controller_inventory_sources is defined
  tags: aap_config_inventory_sources

- name: Configure Controller Labels
  ansible.builtin.import_role:
    name: infra.controller_configuration.labels
  when: controller_labels is defined
  tags: aap_config_labels

- name: Configure Controller Job Templates
  ansible.builtin.import_role:
    name: infra.controller_configuration.job_templates
  when: controller_templates is defined
  tags: aap_config_job_templates

- name: Configure Controller Workflow Templates
  ansible.builtin.import_role:
    name: infra.controller_configuration.workflow_job_templates
  when: controller_workflows is defined
  tags: aap_config_workflow_templates

- name: Configure Controller Schedules
  ansible.builtin.import_role:
    name: infra.controller_configuration.schedules
  when: controller_schedules is defined
  tags: aap_config_schedules

- name: Configure Controller Applications
  ansible.builtin.import_role:
    name: infra.controller_configuration.applications
  when: controller_applications is defined
  tags: aap_config_applications

- name: Create Token on AAP to use for GitHub Workflows
  ansible.builtin.include_tasks: create_token.yml
  loop: "{{ controller_tokens }}"
  loop_control:
    loop_var: __controller_tokens
  when: controller_tokens is defined
  tags: tokens
