---
name: Refresh the RHSM token
# the token expires every 30 days, so we need to refresh it
on:
  schedule:
    - cron: "0 12 1,15 * *"  # run 12pm on the 1st and 15th of the month
  workflow_dispatch:

permissions:
  contents: read

jobs:
refresh:
  runs-on: ubuntu-latest
  steps:
    - name: Refresh the automation hub token
      run: >-
        curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        -d grant_type=refresh_token
        -d client_id=rhsm-api
        -d refresh_token="${{ secrets.RHSM_TOKEN }}"
        --fail --silent --show-error --output /dev/null
